WHLee-HGU/OSSLab_0423_4

contributors/21400217

Dear @WHLee-HGU ,
I have added a text file named with my student ID in the contributor directory.
I hope this commit would be helpful to your project.
Thank you,
Tae Eun.

Added "21400217" to "contributor/"

---

contributors/21700524.txt

@WHLee-HGU 
I have added a new file under the contributors folder.
- Soo Min Lee

New file created.

---

contributors/21600524.txt

Assignment 0423.

---

contributors/21900421.txt

I added a text file entitled "21900421" as my student ID in the directory named "contributors", and I stated to follow Handong CSEE Standard honor code for honesty.

Text file added in the directory named "contributors".

---

contributors/21500329.txt

added 21500329.txt in contributors folder

text file created.

---

contributors/21700372.txt

Professor, I am Minseok Song taking your OpenSource Software class.
I am creating pull request to complete my assignment

new textfile added

---

contributors/21800284.txt

I added 21800284.txt under 'contributors' folder for the  0423 homework.

Add 21800284 text file

---

contributors/21500775.txt

21500775.txt is added  in directory(contributor) for Hw 10 OSS

21500775_KwangyoungHan

---

contributors/21300210.txt

21300210.txt file is added to contributors folder. Thank you.

21300210.txt file is added.

---

contributors/21800706

The file name is '21800706', and the content of the file is honor code.

New file is created

---

contributors/21500014.txt

21500014.txt added.

---

contributors/21600621.txt

branch name: new_branch
updated text file: 21600621.txt

text file updated: Assignment 0423

---

contributors/21300411.txt

Hello, @WHLee-HGU 
The purpose of this pull request is to practice and get accustomed to some git commands.
I added the '21300411.txt' file in the contributors folder.  
Thanks.

21300411.txt added

---

contributors/21400262

0423 assignment : "21400262.txt" is added

text added "21400262.txt"

---

contributors/21700339.txt

@WHLee-HGU  Professor, I have created a new branch that includes a text file with a specific text in it, and the file is named with my student ID.

21700339.txt file created

---

contributors/21700618.txt

@WHLee-HGU 
Hello Professor, let me tell you that a new file has been created, 21700618.txt .

new 21700618.txt

---

contributors/21600362.txt

21600362 this is pull request

---

contributors/21900398.txt

This is 21900398, who are listening OSSLab. I added my assignment text file.

21900398.txt is added

---

contributors/21400615.txt

I made a new branch named hyunjinlee and switched to that branch.
Under the 'contributors' folder, I created a text file '21400615.txt'.

21400615.txt added

---

contributors/21300858.txt

this file is added 04/27.

---

contributors/21700119.txt

Hello, @WHLee-HGU 
I added 21700119.txt in the contributor folder to practice the pull request
Thanks.

text file created

---

contributors/21700592.txt

I made the new branch named, 'new', and inside of it, the newly added file, 21700592.txt, contains my declaration to follow the Handong CSEE Honor Code.

Added my declaration.

---

contributors/21700252.txt

A branch called "newbranch" points to the address of a file called "21700252.txt". In the file, there is a message that I will follow the Honor Code. The commit in this file is "21700252.txt created".

21700252.txt created

---

contributors/21600402

 created 21600402 file and added honor code

---

contributors/21900167

21900167 added.
